name: Deploy
run-name: Deploy started by @${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: BUILD_PATH='./dist' npm run build

      - name: Commit dist
        uses: stefanzweifel/git-auto-commit-action@v4