name: Deploy
run-name: Deploy started by @${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: BUILD_PATH='./dist' npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Rodrigo G Oliveira
          author_email: mjgargani@gmail.com
          add: './dist'
          push: origin dev --force