name: Prepare to GH-Pages
run-name: Validate, build and commit distribution

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Deploy:
    name: File check; Linter; Jest; Build; Commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Key-files change check
        shell: bash
        run: | 
          git fetch origin && \
          if [[ $(git diff --name-only origin/main -- ./.github ./public ./src ./package-lock.json ./package.json ./tsconfig.json) ]]; \
          then true; \
          else echo "Nothing to build in compare with 'main' branch" && exit 1; \
          fi

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint to find warnings and errors
        run: npm run lint -- --max-warnings=0

      - name: Run Jest code tests
        run: npm test

      - name: Build ReactJS project for web
        run: BUILD_PATH='./docs' npm run build

      - name: Commit generated distribution
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'dist: bot commit from ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'